version: '3.3'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=postgresusr
      - POSTGRES_PASSWORD=postgrespwd
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=demodb
      - TZ=Europe/Rome
    ports:
      - '5432:5432'
    volumes: 
      - /tmp/postgresdata:/var/lib/postgresql/data
      - ./postgres/tables.sql:/docker-entrypoint-initdb.d/tables.sql

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: demodb
        DB_USER: postgresusr
        DB_SCHEMA: public
        DB_PASSWORD: postgrespwd
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8085:8080
      volumes: 
      - ./keyclok:/opt/keycloak/data/import
      command: 
      - start-dev 
      - --import-realm
      depends_on:
        - postgres 

volumes:
  db:
    driver: local
    
     